services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chess_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chess_project.settings
