# Generated by Django 5.2 on 2025-04-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='fen',
            field=models.CharField(default='startpos', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
